version: '3.8'

services:
  klasno-app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../index.html:/app/index.html
      - ../vite.config.js:/app/vite.config.js
      - ../tailwind.config.js:/app/tailwind.config.js
      - ../postcss.config.js:/app/postcss.config.js
    environment:
      - NODE_ENV=development
    container_name: klasno-store

volumes:
  node_modules:
